version: "3"
services:
  cudl-tei-processing:
    build:
      context: ./aws-lambda-docker
      dockerfile: Dockerfile
    container_name: cudl-tei-processing
    env_file:
      - .env
    environment:
      TEI_FILE: items/data/tei/*/*.xml
    ports:
      - 9000:8080