version: "3"
services:
  cudl-tei-processing:
    extends:
      file: docker-compose-base.yml
      service: cudl-tei-processing
    environment:
      ENVIRONMENT: local
      TEI_FILE: ${TEI_FILE}
      ANT_TARGET: ${ANT_TARGET:-full}
      COLLECTION_XML_SOURCE: ../dist/collection-xml
      PAGE_XML_SOURCE: ${PAGE_XML_SOURCE}
      CORE_XML_SOURCE: ${CORE_XML_SOURCE}
      SEARCH_HOST: host.docker.internal
      SEARCH_PORT: 8000
    volumes:
      - dist:/tmp/opt/cdcp/dist
      - source:/tmp/opt/cdcp/cudl-data-source
    entrypoint: ["bash", "-c", "-l", "/var/task/local.sh"]
volumes:
  dist:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./dist
  source:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./data